# Generated by Django 6.0.8 on 2026-09-19 10:34

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Author',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(help_text='Имя Автора', max_length=100, verbose_name='First Name')),
                ('last_name', models.CharField(help_text='Фамилия Автора', max_length=100, verbose_name='Last Name')),
                ('middle_name', models.CharField(blank=True, help_text='Отчество Автора', max_length=100, null=True, verbose_name='Middle Name')),
                ('date_of_birth', models.DateField(help_text='Дата рождения Автора', verbose_name='Date of Birth')),
                ('comment', models.TextField(blank=True, help_text='Комментарий к автору', null=True, verbose_name='Comment')),
            ],
            options={
                'verbose_name': 'Автор',
                'verbose_name_plural': 'Авторы',
                'ordering': ['last_name', 'first_name'],
            },
        ),
        migrations.CreateModel(
            name='Book',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='Название книги', max_length=100, verbose_name='Book Name')),
                ('release_date', models.DateField(help_text='Дата публикации книги', verbose_name='Book release date')),
                ('is_rented', models.BooleanField(default=False, help_text='Книга в аренде', verbose_name='Book is rented')),
                ('genre', models.CharField(choices=[('FICTION', 'Художественная литература'), ('NON_FICTION', 'Нехудожественная литература'), ('FANTASY', 'Фэнтези'), ('SCIENCE_FICTION', 'Научная фантастика'), ('MYSTERY', 'Детектив'), ('THRILLER', 'Триллер'), ('ROMANCE', 'Любовный роман'), ('HORROR', 'Ужасы'), ('ADVENTURE', 'Приключения'), ('BIOGRAPHY', 'Биография')], default='FICTION', help_text='Жанр книги', max_length=100, verbose_name='Genre')),
                ('annotation', models.TextField()),
                ('author', models.ForeignKey(help_text='Автор Книги', on_delete=django.db.models.deletion.CASCADE, to='books.author', verbose_name='Author')),
            ],
            options={
                'verbose_name': 'Книга',
                'verbose_name_plural': 'Книги',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='BookMark',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('number_of_marks', models.IntegerField(default=0, help_text='Количество оценок', verbose_name='Marks Count')),
                ('mark_summ', models.IntegerField(default=0, help_text='Количество оценок', verbose_name='Summ og Marks')),
                ('total_mark', models.IntegerField(default=0, help_text='Общая оценка (средняя)', verbose_name='Total Mark')),
                ('book', models.ForeignKey(help_text='Книга', on_delete=django.db.models.deletion.CASCADE, to='books.book', verbose_name='Book')),
            ],
            options={
                'verbose_name': 'Оценка',
                'verbose_name_plural': 'Оценки',
                'ordering': ['total_mark'],
            },
        ),
        migrations.CreateModel(
            name='BookRent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rented_date', models.DateField(help_text='Дата начала аренды', verbose_name='Rent start Date')),
                ('rented_date_end', models.DateField(help_text='Дата окончания аренды', verbose_name='Rent end Date')),
                ('comment', models.TextField(help_text='Комментарий', verbose_name='Comment')),
                ('book', models.ForeignKey(help_text='Книга', on_delete=django.db.models.deletion.CASCADE, to='books.book', verbose_name='Book')),
                ('user', models.ForeignKey(help_text='Пользователь', on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='User')),
            ],
            options={
                'verbose_name': 'Арендованная книга',
                'verbose_name_plural': 'Арендованные книги',
                'ordering': ['book'],
                'unique_together': {('user', 'book')},
            },
        ),
    ]
