# Generated by Django 6.0.8 on 2026-09-26 08:06

import books.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("books", "0002_alter_bookmark_options_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="bookrent",
            name="rented_date_end",
            field=models.DateField(
                default=books.models.rent_period,
                help_text="Дата окончания аренды",
                verbose_name="Rent end Date",
            ),
        ),
    ]
